server:
  port: 8080
  servlet:
    context-path: "/api/auth"

spring:
  data:
    mongodb:
      uri: mongodb+srv://zeldaTheMelda:XLMsssHtYbPZMq9o@gocarshare.yypqzbh.mongodb.net/GoCarShare?retryWrites=true&w=majority
